export { Header } from './Header';
export { GameIntro } from './GameIntro';
export { FloatingControlPanel } from './FloatingControlPanel';
export { PaintingDisplay } from './PaintingDisplay';
export { GameMap } from './GameMap';
export { InstructionsPanel } from './InstructionsPanel';
export { ControlPanel } from './ControlPanel';
export { ResultsDisplay } from './ResultsDisplay';
export { StoryPanel } from './StoryPanel';
